### PR TITLE
Add stack trace

### PR DESCRIPTION
**Pull request by DanielMurphy22**
This PR includes and relates to many changes to the Error Reporter, such as:
- [x]  Disabling receiving Project Recovery files, which we do not use.
- [ ]  Get Mantid to send a Stack Trace https://github.com/mantidproject/mantid/pull/27760
- [ ]  Set up server to clear out old names after 3 months (it seems like there is a useful file in web/services/management/commands/removeolddata.py )
- [x] Change the info displayed to the Slack error-reports channel
- [ ] Are we able to save people's emails and names in their properites file and so the error reporter autofills?

### CODE REVIEW

**Comment by Mantid-Matthew** [comment]
Although has just occurred to me is it worth adding in the task to clear our the old user data here.

**Comment by martyngigg** [comment]
@Mantid-Matthew r.e. your last comment. Is the task to clear out the user data required here?

**Comment by Mantid-Matthew** [comment]
No that suggestion is very much scope creep is not required in this PR

**Comment by martyngigg** [comment]
Ok. Shall I deploy the update now?

**Comment by Mantid-Matthew** [comment]
Yes I think it is good to go. Great work Daniel

**Comment by Mantid-Matthew** [comment]
Although as this will remove some columns from the database may be worth taking a backup of the current database first just in case there are unforeseen consequences.

**Comment by martyngigg** [comment]
I'm thinking we should write a backup script as I now can't quite remember what I did last time!

**Comment by martyngigg** [comment]
One thing that I have just spotted is that if there is an error report to send and you click share all everything then we get `Failed to send recovery data. HTTP response 404` in the log. I think users could think that this means the whole error report failed to send. Should we add back a dummy `/api/recovery` endpoint that just does nothing so that we don't see an error?

It can be removed in the future when we deem enough users are not using a version still accessing that api.

**Comment by DanielMurphy22** [comment]
I will do this!

**Comment by martyngigg** [comment]
Thanks!

**Comment by DanielMurphy22** [comment]
When this is merged and live on the server, it would be worth notifying Tatiana to test if the error report takes a long time to send.

**Pull request merged**
